
# PATHS
train_dataset: ./data/train
validation_dataset: ./data/validation
predict_dataset: ./data/test
#load_model_path: ./weights.103-0.000
output_path: ./

# OPTIMIZATION OPTIONS
loss: MeanSquaredError
optimizer:
  type: Adam
  learning_rate: 0.000403285
  clipnorm: 1.0
  clipvalue: 0.5
metrics: [MeanAbsoluteError]



# TRAINING OPTIONS
batch_size: 32
epochs: 200
epoch_size: 1000
shuffle_training_set: True
shuffle_validation_set: False
val_samples: 100
val_frequency: 1
execute_gpu: False
batch_norm: mean
initial_epoch: 0
